// convert constants
export const CONVERT_SYMBOLS_GET = 'CONVERT_SYMBOLS_GET';
export const CONVERT_SYMBOLS_GET_SUCCESS = 'CONVERT_SYMBOLS_GET_SUCCESS';
export const CONVERT_SYMBOLS_GET_ERROR = 'CONVERT_SYMBOLS_GET_ERROR';

export const CONVERT_CURRENT_CURRENCY_CHANGE = 'CONVERT_CURRENT_CURRENCY_CHANGE';
export const CONVERT_CURRENT_AMOUNT_CHANGE = 'CONVERT_CURRENT_AMOUNT_CHANGE';
export const CONVERT_CURRENT_AMOUNT_CHANGE_VALID = 'CONVERT_CURRENT_AMOUNT_CHANGE_VALID';
export const CONVERT_WANTED_CURRENCY_CHANGE = 'CONVERT_WANTED_CURRENCY_CHANGE';

export const CONVERT_CURRENCY = 'CONVERT_CURRENCY';
export const CONVERT_CURRENCY_SUCCESS = 'CONVERT_CURRENCY_SUCCESS';
export const CONVERT_CURRENCY_ERROR = 'CONVERT_CURRENCY_ERROR';

export const CONVERT_CLEAR_STATE = 'CONVERT_CLEAR_STATE';
