// symbols constants
export const SYMBOLS_GET = 'SYMBOLS_GET';
export const SYMBOLS_GET_SUCCESS = 'SYMBOLS_GET_SUCCESS';
export const SYMBOLS_GET_ERROR = 'SYMBOLS_GET_ERROR';

// convert constants
export const CONVERT_CURRENT_CURRENCY_CHANGE = 'CONVERT_CURRENT_CURRENCY_CHANGE';
export const CONVERT_CURRENT_AMOUNT_CHANGE = 'CONVERT_CURRENT_AMOUNT_CHANGE';
export const CONVERT_CURRENT_AMOUNT_CHANGE_VALID = 'CONVERT_CURRENT_AMOUNT_CHANGE_VALID';
export const CONVERT_WANTED_CURRENCY_CHANGE = 'CONVERT_WANTED_CURRENCY_CHANGE';

export const CONVERT_CURRENCY = 'CONVERT_CURRENCY';
export const CONVERT_CURRENCY_SUCCESS = 'CONVERT_CURRENCY_SUCCESS';
export const CONVERT_CURRENCY_ERROR = 'CONVERT_CURRENCY_ERROR';

export const CONVERT_CLEAR_STATE = 'CONVERT_CLEAR_STATE';

// history constants
export const HISTORY_MY_CURRENCY_CHANGE = 'HISTORY_MY_CURRENCY_CHANGE';
export const HISTORY_OTHER_CURRENCY_CHANGE = 'HISTORY_OTHER_CURRENCY_CHANGE';
export const HISTORY_START_DATE_CHANGE = 'HISTORY_START_DATE_CHANGE';
export const HISTORY_END_DATE_CHANGE = 'HISTORY_END_DATE_CHANGE';
