// convert constants
export const CONVERT_SYMBOLS_GET = 'CONVERT_SYMBOLS_GET';
export const CONVERT_SYMBOLS_GET_SUCCESS = 'CONVERT_SYMBOLS_GET';
export const CONVERT_SYMBOLS_GET_ERROR = 'CONVERT_SYMBOLS_GET';
